#ifndef _FLASH_H
#define _FLASH_H

#include "sys.h"
#include "flash_w25qxx.h"

#define FLASHTYPE W25Q_xx	//flash类型
#define FLASH_SECTOR_SIZE W25QXX_Sector_Size	//flash扇区大小
#define PARAM_SAVED_MAX 4096	//flash最大保存数据个数

//最多4096个参数
//注意：当增加或者减小参数个数时，系统在上电时会自动使用默认值保存新的参数。必须在更改参数前将对应参数默认值设置为当前值！！！
//若没有增加或者减小，只是修改，需要手动保存参数。同样必须在更改参数前将对应参数默认值设置为当前值！！！
typedef enum {
	param_num = 0,	//第一个参数用于记录当前需要保存的参数个数，一定要放在第一个！
	
	sysid_my_gcs = 1,	
	frame_class,
	power_min,
	log_mode,
	ROV_mode_enable,

	health_chenable_imu,
	health_chenable_baro,
	health_chenable_batt,
	health_chenable_joystick,
	health_chenable_gps,
	health_chenable_sd,
	health_chenable_flash,
	
	uartA_baud,	
	uartB_baud,	
	uartC_baud,	
	uartD_baud,	
	uartE_baud,	
	uartF_baud,	
	
	attitude_init_roll,
	attitude_init_pitch,
	attitude_init_yaw,	
	sins_db_x,
	sins_db_y,
	sins_db_z,

	dr_mode,
	wp_path,
	wp_radius_cm, 
	exit_mission_rtl,	
	wp_forward_auto,
	gps_fb_interval,

	throttle_hover,	
	throttle_deadzone_swerve,
	throttle_deadzone_stabilize,
	motor_gain,
	motor_maxGain,
	motor_minGain,
	motor_numGainSetting,
	speed_gain,
	speed_maxGain,
	speed_minGain,
	speed_numGainSetting,
	
	motor1_roll_fac,
	motor1_pitch_fac,
	motor1_yaw_fac,
	motor1_throttle_fac,
	motor1_forward_fac,
	motor1_lateral_fac,
	motor2_roll_fac,
	motor2_pitch_fac,
	motor2_yaw_fac,
	motor2_throttle_fac,
	motor2_forward_fac,
	motor2_lateral_fac,
	motor3_roll_fac,
	motor3_pitch_fac,
	motor3_yaw_fac,
	motor3_throttle_fac,
	motor3_forward_fac,
	motor3_lateral_fac,
	motor4_roll_fac,
	motor4_pitch_fac,
	motor4_yaw_fac,
	motor4_throttle_fac,
	motor4_forward_fac,
	motor4_lateral_fac,
	motor5_roll_fac,
	motor5_pitch_fac,
	motor5_yaw_fac,
	motor5_throttle_fac,
	motor5_forward_fac,
	motor5_lateral_fac,
	motor6_roll_fac,
	motor6_pitch_fac,
	motor6_yaw_fac,
	motor6_throttle_fac,
	motor6_forward_fac,
	motor6_lateral_fac,
	
	remoteCtrl_type,
	remoteCtrl_unConVal_ch1,
	remoteCtrl_unConVal_ch2,
	remoteCtrl_unConVal_ch3,
	remoteCtrl_unConVal_ch4,
	remoteCtrl_unConVal_ch5,
	remoteCtrl_unConVal_ch6,
	remoteCtrl_unConVal_ch7,
	remoteCtrl_unConVal_ch8,
	remoteCtrl_ConVal_ch1_min,
	remoteCtrl_ConVal_ch1_mid,
	remoteCtrl_ConVal_ch1_max,
	remoteCtrl_ConVal_ch2_min,
	remoteCtrl_ConVal_ch2_mid,
	remoteCtrl_ConVal_ch2_max,
	remoteCtrl_ConVal_ch3_min,
	remoteCtrl_ConVal_ch3_mid,
	remoteCtrl_ConVal_ch3_max,
	remoteCtrl_ConVal_ch4_min,
	remoteCtrl_ConVal_ch4_mid,
	remoteCtrl_ConVal_ch4_max,
	remoteCtrl_ConVal_ch5_min,
	remoteCtrl_ConVal_ch5_mid,
	remoteCtrl_ConVal_ch5_max,
	remoteCtrl_ConVal_ch6_min,
	remoteCtrl_ConVal_ch6_mid,
	remoteCtrl_ConVal_ch6_max,
	remoteCtrl_ConVal_ch7_min,
	remoteCtrl_ConVal_ch7_mid,
	remoteCtrl_ConVal_ch7_max,
	remoteCtrl_ConVal_ch8_min,
	remoteCtrl_ConVal_ch8_mid,
	remoteCtrl_ConVal_ch8_max,

	//手柄按钮功能
	btn0_function,
	btn1_function,
	btn2_function,
	btn3_function,
	btn4_function,
	btn5_function,
	btn6_function,
	btn7_function,
	btn8_function,
	btn9_function,
	btn10_function,
	btn11_function,
	btn12_function,
	btn13_function,
	btn14_function,
	btn15_function,
	btn0_sfunction,
	btn1_sfunction,
	btn2_sfunction,
	btn3_sfunction,
	btn4_sfunction,
	btn5_sfunction,
	btn6_sfunction,
	btn7_sfunction,
	btn8_sfunction,
	btn9_sfunction,
	btn10_sfunction,
	btn11_sfunction,
	btn12_sfunction,
	btn13_sfunction,
	btn14_sfunction,
	btn15_sfunction,

	esc_type,

	stream_RAW_SENSORS_freq,				
	stream_EXTENDED_STATUS_freq,
	stream_RC_CHANNELS_freq,
	stream_RAW_CONTROLLER_freq,
	stream_POSITION_freq,
	stream_EXTRA1_freq,
	stream_EXTRA2_freq,
	stream_EXTRA3_freq,
	stream_ALL_freq,
	stream_freq_enable,

	log_TEST_rate, 		
	log_PARAMETER_rate,	
	log_GPS_rate,			
	log_IMU_rate,			
	log_RCIN_rate,			
	log_RCOUT_rate,	
	log_BARO_rate,		
	log_POWR_rate,		
	log_ATTITUDE_rate,		
	log_MODE_rate,		
	log_POS_rate,		
	log_PID_ANG_RLL_rate,	
	log_PID_ANG_PIT_rate,
	log_PID_ANG_YAW_rate,	
	log_PID_RAT_RLL_rate,	
	log_PID_RAT_PIT_rate,	
	log_PID_RAT_YAW_rate,	
	log_PID_ACC_Z_rate,	
	log_PID_VEL_Z_rate,	
	log_PID_POS_Z_rate,	
	log_DR_rate,		
	log_SINS_rate,
	log_WP_rate,			
	log_MODEL_rate,
	
	pidAngleRoll_kp,
	pidAngleRoll_ki,
	pidAngleRoll_kd,
	pidAngleRoll_iLimit,
	pidAngleRoll_outputLimit,
	pidAngleRoll_feedforward,
	pidAnglePitch_kp,
	pidAnglePitch_ki,
	pidAnglePitch_kd,
	pidAnglePitch_iLimit,
	pidAnglePitch_outputLimit,
	pidAnglePitch_feedforward,
	pidAngleYaw_kp,
	pidAngleYaw_ki,
	pidAngleYaw_kd,
	pidAngleYaw_iLimit,
	pidAngleYaw_outputLimit,
	pidAngleYaw_feedforward,
	pidRateRoll_kp,
	pidRateRoll_ki,
	pidRateRoll_kd,
	pidRateRoll_iLimit,
	pidRateRoll_outputLimit,
	pidRateRoll_feedforward,
	pidRatePitch_kp,
	pidRatePitch_ki,
	pidRatePitch_kd,
	pidRatePitch_iLimit,
	pidRatePitch_outputLimit,
	pidRatePitch_feedforward,
	pidRateYaw_kp,
	pidRateYaw_ki,
	pidRateYaw_kd,
	pidRateYaw_iLimit,
	pidRateYaw_outputLimit,
	pidRateYaw_feedforward,
	pidPosZ_kp,
	pidPosZ_ki,
	pidPosZ_kd,
	pidPosZ_iLimit,
	pidPosZ_outputLimit,
	pidPosZ_feedforward,
	pidVelZ_kp,
	pidVelZ_ki,
	pidVelZ_kd,
	pidVelZ_iLimit,
	pidVelZ_outputLimit,
	pidVelZ_feedforward,
	pidAccZ_kp,
	pidAccZ_ki,
	pidAccZ_kd,
	pidAccZ_iLimit,
	pidAccZ_outputLimit,
	pidAccZ_feedforward,
	
	para_last 	//一定要放在最后，用于统计枚举个数
	
}flash_para_list;


//变量类型
typedef enum{
	PARAM_NONE = 0,
	PARAM_INT8,
	PARAM_INT16,
	PARAM_INT32,
	PARAM_FLOAT,
	PARAM_VECTOR3F,
	PARAM_VECTOR6F,
	PARAM_MATRIX3F
}var_type;



void flash_ext_init(void);
void flash_write(u8* pBuffer,u32 WriteAddr,u16 NumByteToWrite);
void flash_read(u8* pBuffer,u32 ReadAddr,u16 NumByteToRead);

void flash_write_core(void);
void flash_parameter_write(void);
void flash_parameter_read(void);
void flash_write_param(u8* param_value,flash_para_list paralist);
//void flash_read_param_u32(flash_para_list,u32* );
//void flash_write_param_u32(u32 ,flash_para_list );


#endif

