#ifndef _GCS_H
#define _GCS_H


//mavlink消息
enum mav_message{
	MSG_HEARTBEAT,
    MSG_ATTITUDE,
    MSG_LOCATION,
    MSG_EXTENDED_STATUS1,
    MSG_EXTENDED_STATUS2,
    MSG_NAV_CONTROLLER_OUTPUT,
    MSG_CURRENT_WAYPOINT,
    MSG_VFR_HUD,
    MSG_SERVO_OUTPUT_RAW,
    MSG_RADIO_IN,
    MSG_RAW_IMU1,
    MSG_RAW_IMU2,
    MSG_RAW_IMU3,
    MSG_GPS_RAW,
    MSG_SYSTEM_TIME,
    MSG_SERVO_OUT,
    MSG_NEXT_WAYPOINT,
    MSG_NEXT_PARAM,
    MSG_STATUSTEXT,
    MSG_LIMITS_STATUS,
    MSG_FENCE_STATUS,
    MSG_AHRS,
    MSG_SIMSTATE,
    MSG_HWSTATUS,
    MSG_WIND,
    MSG_RANGEFINDER,
    MSG_TERRAIN,
    MSG_BATTERY2,
    MSG_CAMERA_FEEDBACK,
    MSG_MOUNT_STATUS,
    MSG_OPTICAL_FLOW,
    MSG_GIMBAL_REPORT,
    MSG_MAG_CAL_PROGRESS,
    MSG_MAG_CAL_REPORT,
    MSG_EKF_STATUS_REPORT,
    MSG_LOCAL_POSITION,
    MSG_PID_TUNING,
    MSG_VIBRATION,
    MSG_RPM,
    MSG_MISSION_ITEM_REACHED,
    MSG_POSITION_TARGET_GLOBAL_INT,
    MSG_ADSB_VEHICLE,
    MSG_BATTERY_STATUS,
    MSG_NAMED_FLOAT,
    //******************************
    MSG_MTI,
    MSG_TCM,
    MSG_MPU,
    //******************************
    MSG_RETRY_DEFERRED // this must be last
};

//向地面站回传消息的种类
enum streams {
	STREAM_RAW_SENSORS,				//传感器原始数据
	STREAM_EXTENDED_STATUS,
	STREAM_RC_CHANNELS,
	STREAM_RAW_CONTROLLER,
	STREAM_POSITION,
	STREAM_EXTRA1,
	STREAM_EXTRA2,
	STREAM_EXTRA3,
	STREAM_PARAMS,
	STREAM_ADSB,
	NUM_STREAMS
};

#endif

